### ISSUE TITLE
Expanding `message` into JSON

### ISSUE THREAD

**Issue by tjaartvdwalt** [thinkst/opencanary#225] opened 2022-12-06 23:33 UTC
I have Webhook configuration similar to an example from the documentation:

```json
"Webhook": {
    "class": "opencanary.logger.WebhookHandler",
    "url": "https://my_upload_url",
    "method": "POST",
    "headers": {
        "Authorization": "Bearer MY_TOKEN",
        "Content-Type": "application/json"
    },
    "data": {"collector": "canary", "content": "%(message)s"},
    "status_code": 200
}
```

I would like the request to have `message` be a json sub document, but with the current syntax it is a string. I have been fiddling around, but I am unable to make it work.

Is it possible to do?

**Comment by joewesch** [comment] 2023-03-22 00:13
Not with the current implementation, no. The WebhookHandler is a sub-class of `logging.Handler` which returns a [Formatter record](https://docs.python.org/3/library/logging.html#formatter-objects) - which is text.

When you send in `application/json` it formats the `data` [dictionary to a string](https://github.com/psf/requests/blob/main/requests/models.py#L511). If what you want in the end is `%(message)s` to just be a part of the dictionary, you can format `data` to be a string and remove the header - essentially doing a `json.dumps` yourself.

I just put in a PR (#237) that will be required for this, but something like this should work afterward:
```json
"Webhook": {
    "class": "opencanary.logger.WebhookHandler",
    "url": "https://my_upload_url",
    "method": "POST",
    "headers": {
        "Authorization": "Bearer MY_TOKEN"
    },
    "data": "{\"collector\": \"canary\", \"content\": %(message)s}",
    "status_code": 200
}
```

**Comment by joewesch** [comment] 2023-05-19 18:48
@tjaartvdwalt The changes that I described have been merged in now. If you are running the latest version from the repo you can try it out and see if it will work for you. If you are running the release version, you will need to wait for a new release before you can try out the changes.

**Comment by hkelley** [comment] 2023-06-20 16:27
I can't speak for other systems,  but at least for Splunk HEC,  this config comes through as JSON ,  (opencanary 0.9.0)

```
				"Webhook": {
						"class": "opencanary.logger.WebhookHandler",
						"url": "https://http-inputs.xxx.splunkcloud.com/services/collector",
						"headers": {
								"Authorization": "Splunk xxxx",
								"Content-Type": "application/json"
						},
						"method": "POST",
						"data": {"host": "enter_node_id", "source":"opencanaryd", "event": "%(message)s"}
				}
```

Tangentially related to the original issue, is there any way to substitute the `node_id` value within `data`?

**Comment by joewesch** [comment] 2023-06-20 22:46
I'm not able to reproduce this. I am using the docker version and I updated my `device.node_id` to `"$HOSTNAME"` as well and this was the output I got when I started the docker container:

```
... 
"logdata": {"msg": {"logdata": "Canary running!!!"}},
"logtype": 1001,
"node_id": "a274757b8576",
"src_host": "",
...
```

Which matches the docker hostname:
```
# echo $HOSTNAME
a274757b8576
```

**Comment by Neleus** [comment] 2023-08-04 06:42
@tjaartvdwalt just use Slack handler as I.
It's default JSON type.

**Comment by jayjb** [comment] 2023-08-07 10:24
Hi @hkelley,

Thanks for writing in. Reading this conversation, I am trying to reproduce your issue. Please can you let me know:
1. How you are running opencanary
2. What OS you are running it on
3. what the webhook config looks like

**Comment by tjaartvdwalt** [comment] 2023-08-16 21:47
@joewesch sorry for taking so long to reply. Your example works perfectly in `0.9`!

As far as I am concerned, the original issue is resolved, but I will keep it open as there are still some secondary issues.

**Comment by jayjb** [comment] 2023-08-17 07:40
Hi @tjaartvdwalt,

Please would you mind opening another issue to  report a different issue. I'm glad the original issue is resolved.

**Comment by jayjb** [comment] 2023-08-18 08:17
I'm closing this issue because the original reporter has had the issue resolved. Please feel free to reopen or create a new issue if there is something new to tackle!

**Closed by jayjb** 2023-08-18 08:17 UTC
Labels: question
