### ISSUE TITLE
Failed to load application: deprecated() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by elschnert** [thinkst/opencanary#229] opened 2023-01-03 09:33 UTC
Starting opencanary via `docker-compose` results in the given error.
It looks like the used python library versions are incompatible right now.

I managed to get the `latest` version running with some modifications, see https://github.com/thinkst/opencanary/commit/782debbfcde44577e06c192d1ac599a1bb802417

As it is more kind of a bandaid (and doesn't solve the issue for `stable`) I didn't create a PR.

**Comment by jayjb** [comment] 2023-02-02 12:21
Hi @elschnert,

Thanks for reporting this. Ill have a look and see what is needed to get it fixed

**Comment by donadelden** [comment] 2023-04-04 16:05
Hi, 

Do you have any updates on this? 

I have the same problem, and the proposed fix does not work for me on the latest code version.

**Comment by jayjb** [comment] 2023-06-23 09:41
Hi @donadelden, 

I'm not hitting the issue on latest or stable for the docker. Could you give me a little more information?

**Comment by jayjb** [comment] 2023-08-07 09:58
Closing this issue because I can't reproduce it. Please re-open the issue with reproduction steps and more details of the host OS.

**Closed by jayjb** 2023-08-07 09:58 UTC
Labels: question
