### ISSUE TITLE
OpenCanary Samba Issue

### ISSUE THREAD

**Issue by ghost** [thinkst/opencanary#166] opened 2021-12-21 04:24 UTC
I have setup OpenCanary in a Ubuntu 20.04 virtualbox VM. (host is Linux Mint) and followed the documentation for setup instructions. However, I'm not able to get Samba share access logged either to the samba-audit.log file, not to a gmail address I setup specially for this. Any help in resolving this would be appreciated.

Thanks

**Comment by Bache** [comment] 2022-01-25 05:09
Having the same issue here. 
Using Ubuntu Server 20.04 LTS, Samba 4.13.14.

SMB share works fine, and the OpenCanary SMB module reports it's up and running, but nothing is ever logged into the samba-audit.log file. I tried manually adding an entry to the samba-audit.log, but no alerts were sent out. I've been over the SMB module Wiki page three times and created the files/folders/permissions requested from scratch each time, with no change.

**Comment by jayjb** [comment] 2022-02-27 08:07
Hi @techminds-max, @Bache,

Sorry for the delay. Im back and investigating. What i have found at the moment is that operation we used to rely on, doesnt seem to trigger anymore: `pread_recv pread_send`. If you change that to `all`, you will notice a bunch of events coming through. 

I'm currently figuring the best operation to listen on.

**Comment by jayjb** [comment] 2022-02-28 08:29
Hi folks,

Yes confirmed that `pread_recv pread_send` isn't working on newer samba versions. Currently, im using the `fstat` operation in the `smb.conf`.

**Comment by Bache** [comment] 2022-03-30 05:11
@jayjb Thank you for checking that out, looks like fstat is logging correctly as you mentioned.

Only issue I have with using fstat is that by simply opening and closing my testing.txt document on my SMB share, it writes ~12 entries to the log, resulting in 12 separate emails. Is there a way to filter these emails to simply receive a single email when a file is opened, or at least a way to group all 12 log entries into a single email notification?

I'm not sure how the old pread operators worked as I hadn't come across this project at this stage, but I'm assuming those would log the way I'm asking?

**Comment by manincharge** [comment] 2022-04-05 03:23
Bache, this is exactly what the correlator was designed to address.

**Comment by jayjb** [comment] 2023-08-08 07:05
Hi @Bache,

@manincharge is correct. We built OpenCanary Correlator to do just that: filter and correlator alerts into notifications that are useful. We have plans to combine correlator into OpenCanary.

Thank you for your digging. We also have plans to improve the SMB experience since new versions of samba keep breaking our module. 

Im closing this issue for now as both problems are on roadmaps to be fixed.

**Closed by jayjb** 2023-08-08 07:05 UTC
Labels: Samba-issue
