### ISSUE TITLE
Error in starting open canary

### ISSUE THREAD

**Issue by naina-emmanuel** [thinkst/opencanary#48] opened 2018-07-31 07:17 UTC
[-] Failed to open opencanary.conf for reading ([Errno 2] No such file or directory: 'opencanary.conf')
[-] Using config file: /home/ubuntu/.opencanary.conf
{"dst_host": "", "dst_port": -1, "local_time": "2018-07-31 07:17:04.528828", "logdata": {"msg": {"logdata": "Added service from class Telnet in opencanary.modules.telnet to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
{"dst_host": "", "dst_port": -1, "local_time": "2018-07-31 07:17:04.532023", "logdata": {"msg": {"logdata": "Added service from class CanaryHTTP in opencanary.modules.http to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
{"dst_host": "", "dst_port": -1, "local_time": "2018-07-31 07:17:04.532878", "logdata": {"msg": {"logdata": "Added service from class CanaryFTP in opencanary.modules.ftp to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
{"dst_host": "", "dst_port": -1, "local_time": "2018-07-31 07:17:04.535660", "logdata": {"msg": {"logdata": "Added service from class CanarySSH in opencanary.modules.ssh to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
{"dst_host": "", "dst_port": -1, "local_time": "2018-07-31 07:17:04.536533", "logdata": {"msg": {"logdata": "Added service from class CanaryMySQL in opencanary.modules.mysql to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
{"dst_host": "", "dst_port": -1, "local_time": "2018-07-31 07:17:04.537040", "logdata": {"msg": {"logdata": "Added service from class CanaryTftp in opencanary.modules.tftp to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
{"dst_host": "", "dst_port": -1, "local_time": "2018-07-31 07:17:04.537537", "logdata": {"msg": {"logdata": "Added service from class CanaryNtp in opencanary.modules.ntp to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
{"dst_host": "", "dst_port": -1, "local_time": "2018-07-31 07:17:04.538014", "logdata": {"msg": {"logdata": "Added service from class CanarySIP in opencanary.modules.sip to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
{"dst_host": "", "dst_port": -1, "local_time": "2018-07-31 07:17:04.538440", "logdata": {"msg": "Canary running!!!"}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}

**Comment by citnadxela** [comment] 2018-07-31 22:53
If I recall correctly (& anyone can correct me if I'm wrong), but I believe it is running.  Look at this first entry:

{"dst_host": "", "dst_port": -1, "local_time": "2018-07-31 07:17:04.538440", "logdata": {"msg": "Canary running!!!"}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}

That's the indicator that Canary is running.  If you then put the IP of the server you're running opencanary from in a browser, it should take you to a Synology page.  From there, if you take a look at the logs, you'll see the IP of the computer that visited the Synology page.  Hope this helps.

**Comment by naina-emmanuel** [comment] 2018-08-01 06:13
Yes, its getting me to the synology page but i can't sign in to that...

**Comment by thinkst** [comment] 2018-08-01 08:09
hey @naina-emmanuel,

As @citnadxela mentioned, the opencanary is running those services; and from those logs you can see that the http service has been started. 

The http service you are running is probably the synology web skin, which means that if you navigate to the address running the opencanary daemon in your browser (so it will try port 80), you will see the synology page. You will not be able to log in because it is a fake service that is designed to look like the real thing (to tempt unwelcome guests on your network to try login).

With regards to Samba, you will need to have a Samba share running separately and point the opencanary Samba fake service towards your real Samba log file. The opencanary will then monitor the Samba log file you specified in the `opencanary.conf`. 

You can then test the Samba service by accessing files in the Samba share and making sure you generate an alert. 

Please let me know if this helps (or if there is anything else I can help with)

**Comment by naina-emmanuel** [comment] 2018-08-01 08:48
@thinkst can I have a tutorial of how to test the samba service? As opencanary is running and I am getting logs of visiting synology page in /var/tmp/opencanary.log

**Comment by thinkst** [comment] 2018-08-16 09:49
Hi @naina-emmanuel,

Sorry for the delay. The Samba service portion of Opencanary requires that you have a working Samba service running on the same machine as the Opencanary daemon. 

So you will need to setup a Samba service on your machine. You can then test that it is working by adding some files to the Samba File Share and checking that you are able to access them. Also keep your Samba config ready as some of those details will need to go into the OpenCanary config file. (you can take the testing a step further and check that log lines are being written to `/var/log/samba-audit.log`)

Once you have confirmed the above is running, you will need to configure your Opencanary to use that Samba file share instance. To do this, you will need to insert the required values in the OpenCanary config file. These values are the ones prefix'ed with `smb`. In particular, you will need to change `smb.configfile`, `smb.enabled`, `smb.filelist`, `smb.sharename` and `smb.workgroup`. For getting the initial Samba setup, look to setting it up in Workgroup mode (not domain joined). 

Once this is all setup, you can restart the OpenCanaryd daemon. Then you can try testing by accessing the files you specified in `smb.filelist` and seeing that you get an alert (and that it is being logged).

I hope this gets you going in the right direction. Please let me know how it goes (or how I may help further)

**Comment by citnadxela** [comment] 2018-12-03 23:37
@naina-emmanuel hate to bring this up again, but were you ever able to get the Samba portion to work?  Got some free time & want to go back to playing around wi/ opencanary because it's so good, but I, myself, am confused wi/ this.

**Comment by hydrogencn** [comment] 2019-05-29 22:04
Hi @thinkst, I'm having similar issues as the other two posters. Here's what I've tried:

in /home/user/.opencanary.conf I have:

...
"smb.enabled": true,
    "smb.configfile": "/etc/samba/smb.config",
    "smb.filelist": [
        {
            "name": "passwords.txt",
            "type": "TXT"
        },
        {
            "name": "passwords.docx",
            "type": "DOCX"
        }
    ],
    "smb.sharename": "Confidential Documents",
    "smb.workgroup": "workgroup",
    "smb.auditfile": "/var/log/samba-audit.log",
...

and in /etc/samba/smb.conf I have:

...
[global]
    workgroup = workgroup
    server string = Windows 2012 File Server
    dns proxy = no
    log file = /var/log/samba-audit.log
    max log size = 1000
    usershare path =
    log level = 2
    vfs object = full_audit
    full_audit:prefix = %U|%I|%i|%m|%S|%L|%R|%a|%T|%D
    full_audit:success = pread
    full_audit:failure = none
    full_audit:facility = local7
    full_audit:priority = notice
    max log size = 100

    panic action = /usr/share/samba/panic-action %d
    server role = standalone server
    passdb backend = tdbsam
    obey pam restrictions = yes
    unix password sync = no
    passwd program = /usr/bin/passwd %u
    passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
    pam password change = yes
    map to guest = bad user

[Confidential Documents]
    comment = Human Resource Documents Backup
    path = /home/user/share
    guest ok = yes
    read only = yes
    browseable = yes
...


After restarting Samba and OpenCanary, I'm expecting OpenCanary to pick up the audit file set to samba-audit.log. The passwords.txt file exists and when I open it, the event is logged to /var/log/samba-audit.log, but I don't receive a notification. Notifications work for other services that are enabled (HTTP and RDP). I've tried moving the log file to home and /var/log/samba/log.all to no avail.

If you could point me in the right direction for what I'm missing, I would appreciate it.

**Comment by jayjb** [comment] 2019-06-13 08:51
Hey @hydrogencn,

Sorry for the delay. I have a quick test for you to try, would you mind changing your `smb.conf`to reflect `full_audit:prefix = %U|%I|%i|%m|%S|%L|%R|%a|%T|%d`. We saw a strange issue where the issue was resolved by a user making that change.

We are having a hard look at the `samba.py` working soon, so I suspect there will be some changes soon to help get it running smoother and easier. Let me know if this works, otherwise we can continue debugging.

**Comment by hydrogencn** [comment] 2019-06-13 18:52
Hi, thanks for the reply. Here is my updated smb.conf:

[global]
workgroup = workgroup
server string = Windows 2012 File Server
dns proxy = no
log file = /var/log/samba-audit.log
max log size = 1000
usershare path =
log level = 2
vfs object = full_audit
#full_audit:prefix = %U|%I|%i|%m|%S|%L|%R|%a|%T|%D
full_audit:prefix = %U|%I|%i|%m|%S|%L|%R|%a|%T|%d
full_audit:success = pread
full_audit:failure = none
full_audit:facility = local7
full_audit:priority = notice
max log size = 100
panic action = /usr/share/samba/panic-action %d
server role = standalone server
passdb backend = tdbsam
obey pam restrictions = yes
unix password sync = no
passwd program = /usr/bin/passwd %u
passwd chat = Enter\snew\s\spassword:* %n\n Retype\snew\s\spassword:* %n\n password\supdated\ssuccessfully .
pam password change = yes
map to guest = bad user

[Confidential Documents]
comment = Human Resource Documents Backup
path = /home/user/share
guest ok = yes
read only = yes
browseable = yes

Still not sending email alerts, but things are definitely getting logged to the samba-audit.log. If the samba part is under heavy development, I can wait or if there are helpful logs I can provide, let me know.

**Comment by ajhubs** [comment] 2019-08-05 22:26
In case it helps anyone, once I had samba working and a working file share, I had to have port scan enabled, before accessing the share would trigger an event.

Relevant section of .opencanary.conf below

"portscan.enabled": true,
    "portscan.logfile":"                                                                                                           ",
    "portscan.synrate": 5,
    "portscan.nmaposrate": 5,
    "portscan.lorate": 3,
    "smb.auditfile": "/var/log/samba-audit.log",
    "smb.enabled": true,

**Comment by hydrogencn** [comment] 2019-08-12 17:14
@ajhubs 

This did help, thanks! The email notification takes about 20 minutes to send, but the data reported works, so that works for me!

**Comment by jayjb** [comment] 2019-09-30 17:00
Hi @ajhubs, @hydrogencn,

Just to be clear with regards to the Samba module; it should only alert on open files not on simply browsing the file share (or atleast that was not our intention). If this is something you would find useful, we can add it to the feature list. 

@ajhubs: thanks for finding a workaround though. Im sure thats useful for other users too. 

@hydrogencn: the 20 minute time to send an email doesn't sound right. Would you mind trying to enable a different alerting mechanism? or even running it in `--dev` mode to see if the alerts are being logged there instantly?

**Closed** 2020-10-06 18:43 UTC
