### ISSUE TITLE
Error When Starting OpenCanary

### ISSUE THREAD

**Issue by hamza005** [thinkst/opencanary#23] opened 2016-10-11 22:08 UTC
Can Someone help me please. I have an issue when starting the opencanary. I'm not a programmer so can't handle this issue on my behalf. 
![screenshot from 2016-10-12 03-07-47](https://cloud.githubusercontent.com/assets/20417498/19290429/1d3df13a-9029-11e6-8231-e3acc68556b4.png)

**Comment by thinkst** [comment] 2016-10-12 15:06
Hi, this is a duplicate of #15 and should fixed. Please check that you've created your config from the default included in the latest source. If it's still an issue, please post a copy of the config file you're using.

**Comment by hamza005** [comment] 2016-10-12 16:16
{
    "device.bluetooth.name": "canary",
    "device.node_id": "hamza",
    "ftp.banner": "FTP server ready",
    "ftp.enabled": true,
    "ftp.port":21,
    "http.banner": "Apache/2.2.22 (Ubuntu)",
    "http.enabled": true,
    "http.port": 80,
    "http.skin": "nasLogin",
    "http.skin.list": [
        {
            "desc": "Plain HTML Login",
            "name": "basicLogin"
        },
        {
            "desc": "Synology NAS Login",
            "name": "nasLogin"
        }
    ],
    "httpproxy.port": 8080,
    "httpproxy.skin": "squid",
    "httproxy.skin.list": [
        {
            "desc": "Squid",
            "name": "squid"
        },
        {
            "desc": "Microsoft ISA Server Web Proxy",
            "name": "ms-isa"
        }
    ],
    "logger": {
        "class" : "PyLogger",
        "kwargs" : {
            "formatters": {
                "plain": {
                    "format": "%(message)s"
                }
            },
            "handlers": {
                    "SMTP": {
   "class": "logging.handlers.SMTPHandler",
                    "mailhost": ["smtp.gmail.com", 25],
                    "fromaddr": "hhumza673@gmail.com",
                    "toaddrs" : ["hamzajavaidkathana@gmail.com"],
                    "subject" : "OpenCanary Alert"
},
                "console": {
                    "class": "logging.StreamHandler",
                    "stream": "ext://sys.stdout"
                  },

             "file": {
                    "class": "logging.FileHandler",
                    "filename": "/var/tmp/opencanary.log"
                },
                "syslog-unix": {
                    "class": "logging.handlers.SysLogHandler",
                    "address": ["localhost", 514],
                    "socktype": "ext://socket.SOCK_DGRAM"
                },
                "json-tcp": {
                    "class": "opencanary.logger.SocketJSONHandler",
  "host": "127.0.0.1",
                    "port": 1514
                },

    "hpfeeds": {
                    "class": "opencanary.logger.HpfeedsHandler",
                    "host": "127.0.0.1",
                    "port": 10000,
        "ident": "test",
        "secret":"12345",
        "channels":["test.events"]
                }
            }
        }
    },
    "portscan.synrate": "5",
    "smb.auditfile": "/var/log/samba-audit.log",
    "smb.configfile": "/briar/config/smb.conf",
    "smb.domain": "corp.thinkst.com",
    "smb.enabled": false,
    "smb.filelist": [
           {
            "name": "2016-Tender-Summary.pdf",
            "type": "PDF"
        },
        {
            "name": "passwords.docx",
            "type": "DOCX"
        }
    ],
    "smb.mode": "workgroup",
    "smb.netbiosname": "FILESERVER",
    "smb.serverstring": "Windows 2003 File Server",
    "smb.sharecomment": "Office documents",
    "smb.sharename": "Documents",
    "smb.sharepath": "/changeme",
    "smb.workgroup": "OFFICE",
    "mysql.banner": "5.5.43-0ubuntu0.14.04.1",
    "mysql.port": 3306,
    "mysql.enabled": true,
    "ssh.enabled": true,
    "ssh.port": 8022,
    "ssh.version": "SSH-2.0-OpenSSH_5.1p1 Debian-4",
    "rdp.enabled": false,
"sip.enabled": true,
    "snmp.enabled": false,
    "ntp.enabled": true,
    "tftp.enabled": true,
    "ntp.port": "123",
    "telnet.port": "23",
    "telnet.enabled": true,
    "telnet.banner": "",
    "telnet.honeycreds" : [

 {
            "username" : "admin",
            "password" : "$pbkdf2-sha512$19000$bG1NaY3xvjdGyBlj7N37Xw$dGrmBqqWa1okTCpN3QEmeo9j5DuV2u1EuVFD8Di0GxNiM64To5O/Y66f7UASvnQr8.LCzqTm6awC8Kj/aGKvwA"

        },
        {
            "username" : "admin",
            "password" : "admin1"
        }
    ],
    "mssql.enabled": false,
    "vnc.enabled": false
}

this is the conf file and issue is still there not resolved.

**Comment by hamza005** [comment] 2016-10-12 16:19
![screenshot from 2016-10-12 03-19-35](https://cloud.githubusercontent.com/assets/20417498/19318268/7a533892-90c1-11e6-8516-40476e407225.png)

**Comment by thinkst** [comment] 2016-10-13 15:02
You can fix this issue by deleting the following `hpfeeds` section:

```
"hpfeeds": {
                "class": "opencanary.logger.HpfeedsHandler",
                "host": "127.0.0.1",
                "port": 10000,
    "ident": "test",
    "secret":"12345",
    "channels":["test.events"]
            }
        }
    }
},
```

However, this looked like it should have been fixed in #15. Is this config from the latest version? How did you get it?

**Comment by thinkst** [comment] 2017-02-15 07:56
Closing due to inactivity.

**Closed by thinkst** 2017-02-15 07:56 UTC

**Comment by hamza005** [comment] 2017-02-16 06:34
Okay, The problem has been solved. Sorry for not informing you in the time.
Good luck.


Regards
Hamza Javaid
Applied Security Engineering and research group Islamabad.
